pipeline {

    agent any


    stages {


        stage('Checkout Code') {

            steps {

                git branch: 'main',
                credentialsId: 'hs-44',
                url: 'https://github.com/hs-44/Jenkins_sonarcube_docker.git'

            }
        }



        stage('Deploy To Docker Server') {

            steps {


                sshagent(['ubuntu_docker']) {


                    sh '''

                    ssh -o StrictHostKeyChecking=no ubuntu@3.95.252.192 "
                    mkdir -p ~/website
                    "


                    scp -o StrictHostKeyChecking=no -r \
                    fruitkha-1.0.0 \
                    ubuntu@3.95.252.192:~/website/


                    ssh -o StrictHostKeyChecking=no ubuntu@3.95.252.192 "

                    cd ~/website/fruitkha-1.0.0


                    docker rm -f fruitkha-website || true


                    docker build -t mywebsite1 .


                    docker run -d \
                    -p 8086:80 \
                    --name fruitkha-website \
                    mywebsite


                    "


                    ssh -o StrictHostKeyChecking=no ubuntu@3.95.252.192 "

                    docker ps

                    "


                    '''

                }

            }

        }


    }

}
